### ISSUE TITLE
[Device UART] Add Docker Hub description

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-uart#22]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 Docker hub overview descriptions

### Description [**REQUIRED**]
All EdgeX docker images have overview descriptions in docker hub 
Example: https://hub.docker.com/r/edgexfoundry/device-onvif-camera

Device UART doesn't yet have this:
https://hub.docker.com/r/edgexfoundry/device-uart
https://hub.docker.com/r/edgexfoundry/device-uart-arm64

### Describe the solution you'd like
New descriptions must be added to https://github.com/edgexfoundry/cd-management/tree/edgex-docker-hub-documentation
Add service to https://github.com/edgexfoundry/cd-management/blob/edgex-docker-hub-documentation/descriptions/image_descriptions.txt
Add MD files to: https://github.com/edgexfoundry/cd-management/tree/edgex-docker-hub-documentation/image-overview-templates/new-names
- Use https://github.com/edgexfoundry/cd-management/blob/edgex-docker-hub-documentation/image-overview-templates/new-names/device-onvif-camera.md as template for non-arm64
- Use  https://github.com/edgexfoundry/cd-management/blob/edgex-docker-hub-documentation/image-overview-templates/new-names/device-onvif-camera-arm64.md as template for non-arm64

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by cloudxxx8** [comment]
@sudhamani-hcl could you or your team help take care of this issue?  thanks.

**Comment by vediyappan-hcl** [comment]
@cloudxxx8 I tried cloning the cd-management repo. After cloning I could see, only README.md file is present inside `cd-management` directory. 

However, I was able to download the source zip with `https://github.com/edgexfoundry/cd-management/archive/refs/heads/main.zip` and added service to https://github.com/edgexfoundry/cd-management/blob/edgex-docker-hub-documentation/descriptions/image_descriptions.txt file and MD files in https://github.com/edgexfoundry/cd-management/tree/edgex-docker-hub-documentation/image-overview-templates/new-names. Hence I have the changes locally which need to be committed. Please suggest how to clone all the files, so that I can commit the changes.

```
vediyappan@vediyappan-ThinkPad-P15-Gen-1:~/work$ git clone https://github.com/edgexfoundry/cd-management.git
Cloning into 'cd-management'...
remote: Enumerating objects: 3551, done.
remote: Counting objects: 100% (3551/3551), done.
remote: Compressing objects: 100% (1044/1044), done.
remote: Total 3551 (delta 2326), reused 3536 (delta 2320), pack-reused 0
Receiving objects: 100% (3551/3551), 7.43 MiB | 3.11 MiB/s, done.
Resolving deltas: 100% (2326/2326), done.
vediyappan@vediyappan-ThinkPad-P15-Gen-1:~/work$ cd cd-management/
vediyappan@vediyappan-ThinkPad-P15-Gen-1:~/work/cd-management$ ls -lt
total 4
-rw-rw-r-- 1 vediyappan vediyappan 2073 Aug 18 19:54 README.md
vediyappan@vediyappan-ThinkPad-P15-Gen-1:~/work/cd-management$

```

**Comment by lenny-intel** [comment]
@sudhamani-hcl , once you create a fork of cd-management, you must do a git fetch --all and then checkout the `edgex-docker-hub-documentation` branch. The create you PR branch from that and submit the PR against the  `edgex-docker-hub-documentation`  branch when creating the PR.

**Comment by vediyappan-villali** [comment]
@lenny-intel Thanks for the details. Committed the changes, created the PR and submitted it. Please check https://github.com/edgexfoundry/cd-management/pull/366.
